manifest = "70e0235a4364272dc96094a4971b1a3e7503e2f53c7531015bed78017805d12d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.65.1" ]
revision = "fe9dc8ff7926e3e7d01c0cd6fa039c758cfb422b"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.1" ]
revision = "306bfa59b6c7de6b2079d295b052a8d97a5248bf"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "debf71b9eb1f3a4d6a3d2bed838520b2f6641841"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.1" ]
revision = "558ea1c4a33ce1b788bb4d7f18c0e20939adf6b1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "3838f909c0f1c5b5a9c7c775c68b92234b450146"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.65.1" ]
revision = "8e6efa01d89422ae22eb0eac342e5359a93cf07a"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.65.1" ]
revision = "9257d861cbc483199c8c125f05c278fa0f3fa0cd"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.65.1" ]
revision = "fb1479992bf8d63e4b2194dbd5a22e5c9e88cae7"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.65.1" ]
revision = "55139832dc19b434bc5e6cac61f2b776a224620f"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.65.1" ]
revision = "e24910966d7630e371e8dff04a74d4e8921162f0"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.1" ]
revision = "1f0d010def9d751df46fc68fb59568c0d57aa957"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.65.1" ]
revision = "799b7cd3dbebd41a3a88ad667bee3d96917e53f2"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.1" ]
revision = "fb23e2cb271ddcc265cb630bd7e26083bad8d32a"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.65.1" ]
revision = "99e8dff8c8b932ab7a29404ac363551a3bcc81c8"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "73bbde0665120a5743454c4eb96c26de6a0c2a83"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.65.1" ]
revision = "526215de29e2e5f4d4a49805963d4c88a664c200"
