targets = [ "//:format" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.34.1"

