manifest = "b9ac506863d268892f912091353386e610eba00038310f1d34d1bfd8a468197d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.69.0" ]
revision = "fafdc735d8f216470c143aa264adc66dd905a1b8"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.69.0" ]
revision = "7efa27c40f71ece30046a6cef004ff8c3005c0db"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.69.0" ]
revision = "a201a6ed68dd2940f92571d0abf9b1a34bf132fb"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.69.0" ]
revision = "038f11b5f989d69494be573e15e691298badb41d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.69.0" ]
revision = "d8edec0d4bf89464bddf60a1f5b509380fa31cd9"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.69.0" ]
revision = "3df43bd202a9df43c4143b376755daa20ee29c76"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.69.0" ]
revision = "483faec375bc614a83c67787720e41345c624ba1"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.69.0" ]
revision = "fd37185ae394fee43e858b36000a950564bdced9"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.69.0" ]
revision = "6b5e5055b3e136b6e1cf51e6dfe8e950d3c8ab26"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.69.0" ]
revision = "9b47959df84a86432d59e4eb1aeb2a8b3880cae1"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.69.0" ]
revision = "7140552f699ddf94c4eedc04f58d97df381dfd1a"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.69.0" ]
revision = "205737a1e96d8c37168738a1c73bca98647c53d2"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.69.0" ]
revision = "09ea55c7ec4a8507d5c883627c9c0426dec87099"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.69.0" ]
revision = "5c7b4b92070eec3e5beebc2b58bf0296ad0e18d9"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.69.0" ]
revision = "b4786d4c7be1adeee18fa134a3d7507a250d9678"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.69.0" ]
revision = "851b6909a502c187cf5ce8fdd9bbc7bcca0b83ec"
